name: Cypress Tests

on: push

env:
  RESAS_API_URL: ${{secrets.RESAS_API_URL:}}
  RESAS_API_KEY: ${{secrets.RESAS_API_KEY}}
  RESAS_PREFECTURES_API: ${{secrets.RESAS_PREFECTURES_API}}
  RESAS_POPULATION_API: ${{secrets.RESAS_POPULATION_API}}

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          
